version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  clustered_version:
    build:
      context: ./clustered_version
    depends_on:
      - postgres

  non_clustered_version:
    build:
      context: ./non_clustered_version
    depends_on:
      - postgres

